"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional


@dataclasses.dataclass
class AddUsageMetricsFromSushiRepoRequest:
    id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'id', 'style': 'simple', 'explode': False }})
    report_on_disk: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'reportOnDisk', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class AddUsageMetricsFromSushiRepoResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    

